compile FILE:
    #!/usr/bin/zsh
    cargo run -- test_codes/{{FILE}}.ipu --output test_codes/{{FILE}}.ll
    llc-12 ./test_codes/{{FILE}}.ll
    gcc ./test_codes/{{FILE}}.s -o ./test_codes/{{FILE}}

run FILE:
    #!/usr/bin/zsh
    just compile {{FILE}}
    ./test_codes/{{FILE}}