[package]
name = "ipulang-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
anyhow = "1"
nom = "7"
nom_locate = "4.0.0"